name: 'Pull request: Run unit test'

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

#      - name: Download dependencies
#        run: ./mvnw clean install

      - name: Test
        run: ./mvnw test